---
title: "Scenario"
author: "Camilla Novaglio"
date: "05/11/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

#-----------------------------------------
# upload codes and data 
#----------------------------------------------

```{r}

rm(list=ls())
load("/Users/camillan/Dropbox/Mizer-fleet_extension/data/FDData_opn3_24112020.RData") 

library(plyr)
library(tidyverse)
library(reshape2)
library(ggplot2)
library(dplyr)
library(matrixStats)
library(mizer)

setwd("/Users/camillan/R-projects/Mizer-fleet/R")
source("data.R") 
source("help.R") 
source("MizerParams-class.R") 
source("MizerSim-class.R")
source("plots.R")
source("project_methods.R")
source("project.R") 
source("RcppExports.R") 
source("selectivity_funcs.R")
source("summary_methods.R")
source("wrapper_functions.R")
source("DataFunction.R") 

#  options are sim_FD_bmsy and df_param2, or sim_FD_bmsy_no_erepro_fix and df_param
sim = sim_FD_bmsy
df_param = df_param2
interaction = theta
kappa = kappa
kappa_ben = kappa_ben
kappa_alg = kappa_alg
w_pp_cutoff = w_pp_cutoff
min_w_bb = 1e-7 # min_w_bb # from SEAmodel_run.R - accidentally removed from the list above # added now .... rerun previous stem 
w_bb_cutoff = w_bb_cutoff
fleetDynamics = TRUE
selectivity_params = df_selParam_new
catchability = df_target_bmsy2
target = df_target_bmsy2
effort = 0
dt = 0.25
management = TRUE
price = df_price_new
cost = df_cost3
diet_steps = 0
ke = ke_fleet
scaling_price = scaling_price
Blevel_management = "Bmsy"
initial_n = initial_n
initial_n_pp = initial_n_pp
initial_n_bb = initial_n_bb
initial_effort = initial_effort2

```

#-----------------------------------------
# target matrix for each scenario
#----------------------------------------------

```{r}

####### initial community
initial_n_scenario = sim@n[nrow(sim@n),,]
initial_n_pp_scenario  = sim@n_pp[nrow(sim@n_pp),]
initial_n_bb_scenario  = sim@n_bb[nrow(sim@n_bb),]
initial_effort_scenario = sim@effortOut[dim(sim@effortOut)[1],]   

####### forward price and costs
t_max = 23 # 23 # till 2040 (23) or 2100 (83) or eql (500?)
price_forward = t(replicate(t_max, price[nrow(price),]))
rownames(price_forward)<-seq(1:t_max) # or...
rownames(price_forward)<-seq(2018,(2018+t_max-1))

cost_forward1 <- t(replicate(t_max, cost[nrow(cost),,1]))
rownames(cost_forward1)<-seq(1:t_max) # or ... 
rownames(cost_forward1)<-seq(2018,(2018+t_max-1))

cost_forward2 <- t(replicate(t_max, cost[nrow(cost),,2]))
rownames(cost_forward2)<-seq(1:t_max) # or ...
rownames(cost_forward2)<-seq(2018,(2018+t_max-1))

cost_forward <-array(c(cost_forward1,cost_forward2), dim = c(t_max,dim(cost)[2],dim(cost)[3])) # or ...
cost_forward <-array(c(cost_forward1,cost_forward2),dim = c(dim(cost_forward1)[1],dim(cost)[2],dim(cost)[3]), dimnames = c(dimnames(cost_forward1)[1],dimnames(cost)[2],dimnames(cost)[3]))

######## check that Fmort from all fleets is <1 i.e. exploitation rate (catch/biomass at t) < 1 

######## target unfished 
df_target_unfished<-target
df_target_unfished[]<-0

####### status quo 
#target>0.005 # managemtn only applies to those species - it's a rule within the managemtn component taht was there to avoid fleets collapses and reproduce historical trensds but it does change things a lot and it may be the reason why status quo and no bycatch are the same 

#target>0 & target<0.005 # fished but not managed
# SSG: sillago, gauldi, tracurus, centroberix, nemadactylus (!), platy (!! but OK as this is the shark hook an dgillnet sector and platy is not a mian spp), faber (!), macrurus, seriorella p, rexea
# SED helicolenus, centroberix, squalus (!!), macrurus, serio p, rexea, genipt, galeo (!)
# DS: gauldi, tracurus, squalus, macrurus, rexea
# SH: gauldi (!), helicolenus, trachurus, 
# US; trachurus, pristo, mustelus

######## no competition
df_target_NoCompetition<-target
trial<-colMaxs(df_target_NoCompetition)
trial<-trial[-which(trial == 0)]
df_target_NoCompetition[df_target_NoCompetition %in% trial]<-1
df_target_NoCompetition[df_target_NoCompetition != 1]<-0

#df_target_NoCompetition>0.005 # here it does not apply as none is under management

# keep Fmort constant across scenarios  
div<-colSums(df_target_NoCompetition*initial_effort_scenario)/colSums(target*initial_effort_scenario)
df_target_NoCompetition<-sweep(df_target_NoCompetition, 2, div, FUN = '/')
df_target_NoCompetition[, "myctophids"]<-0  

colSums(df_target_NoCompetition*initial_effort_scenario)
colSums(target*initial_effort_scenario)

######## full competition 
df_target_FullCompetition<-target
df_target_FullCompetition[]<-1
df_target_FullCompetition[, "myctophids"]<-0  

# keep Fmort constant across scenarios 
div<-colSums(df_target_FullCompetition*initial_effort_scenario)/colSums(target*initial_effort_scenario)
df_target_FullCompetition<-sweep(df_target_FullCompetition, 2, div, FUN = '/')
df_target_FullCompetition[, "myctophids"]<-0  

colSums(df_target_FullCompetition*initial_effort_scenario)

#df_target_FullCompetition>0.005 # here it does not apply as they are all under management

######## no bycatch (and spp under recovery strategies) 
# NOTE: 2 fisheries are based on spp under recovery strategies - OR and school shark
df_target_NoBycatch<-target

# bycatch defined as: the 2 fleets with lowest proportion of catches should not catch the spp 
df<-target
for(i in 1:ncol(df)){
  df<-df[order(df[,i]),]
  df[c(1,2,3),i]<-0
}
df<-df[c(2,1,4,3,5),]
df_target_NoBycatch<-df

# keep Fmort constant across scenarios 
div<-colSums(df_target_NoBycatch*initial_effort_scenario)/colSums(target*initial_effort_scenario)
df_target_NoBycatch<-sweep(df_target_NoBycatch, 2, div, FUN = '/')
df_target_NoBycatch[, "myctophids"]<-0  

colSums(df_target_NoBycatch*initial_effort_scenario)

#df_target_NoBycatch>0.005 # here it  only applies to thracurs because all other target are fished >0.005 and under management  

# what's the difference with target?! 
#target>0.005 # nemadactylus, platy, zeus, serio, genipterus, pristo, mustelus, galeo are targeted by 3 or more fleets, so it should be OK anyway. But target values for the spp commonly caught in target and bycatch are higher in bycatch because you redistributed effort across the target speies - this means 1) fmort is higher for the target and managed spp in bycatch and if these are depleted managemnt forces steeper decreases; 2) however, more speceis are managed under target which means again steeper decreases.  Alos, this rule applies to managemtn and not Fmort - spp that are <0.005 in target will still be fished.   
#target<0.005

######## more valuable     
# define most valuable spp and increase fishing by 50% 
# prices checked according to data, sharks have highest values 
valuable<-sort(-df_price_new[nrow(df_price_new),])
valuable<-names(valuable)[1:6]

# increase Fmort of valuable by 50% of current Fmort and spread that increase across fleets proportionally
df_target_MoreTarget<-target
a<-colSums(target[,valuable]*initial_effort_scenario) 
a<-a + (a*0.5) 
div<-colSums(df_target_MoreTarget[,valuable]*initial_effort_scenario)/a
df_target_MoreTarget[,valuable]<-sweep(df_target_MoreTarget[,valuable], 2, div, FUN = '/')

colSums(df_target_MoreTarget*initial_effort_scenario)

#df_target_MoreTarget>0.005 # same as for target but mustelus/US which is not managed in target - effort increase here becasue it's a more valuable speceis 

#target>0.005

######## target more under-quota   
# define under quota spp and increase fishing on these by 50%. https://www.afma.gov.au/sites/default/files/semac_tac_recommendations_2019-20.pdf
under<-c("macruronus novaezelandiae","nemadactylus macropterus","zeus faber","pristiophorus cirratus") 

# increase Fmort of under-quota by 50% of current Fmort and spread that increase across fleets proportionally
df_target_MoreUnderQuota<-target
a<-colSums(target[,under]*initial_effort_scenario) 
a<-a + (a*0.5)
div<-colSums(df_target_MoreUnderQuota[,under]*initial_effort_scenario)/a
df_target_MoreUnderQuota[,under]<-sweep(df_target_MoreUnderQuota[,under], 2, div, FUN = '/')

colSums(df_target_MoreUnderQuota*initial_effort_scenario)

#df_target_MoreUnderQuota>0.005 # macrurus is managed in DS and prist is managed in US 
#target>0.005

# does this also influences the number of spp above/below ref limits in my indicators plot?? NO


```

#-----------------------------------------
# run scenarios and save data 
#----------------------------------------------

```{r}

target_scenario = list(unfished = df_target_unfished, noCompetition = df_target_NoCompetition, fullCompetition = df_target_FullCompetition, statusQuo = target, noBycatch = df_target_NoBycatch, MoreTarget = df_target_MoreTarget, MoreUnderQuota = df_target_MoreUnderQuota) 

# see original code for additional sets of scenarios (e.g pathway tono competition, management scenarios, size-selectivity scenarios)

runModel<-function(target_scenario){
  
  params_scenario<-list()
  sim_scenario<-list()

  for(i in 1:length(target_scenario)){
  
    params_scenario[[i]] <- MizerParams(df_param,
                            interaction = theta, 
                            kappa = kappa,
                            kappa_ben = kappa_ben, 
                            kappa_alg = kappa_alg, 
                            w_pp_cutoff = w_pp_cutoff,
                            min_w_bb = min_w_bb, 
                            w_bb_cutoff = w_bb_cutoff, 
                            fleetDynamics = TRUE, 
                            selectivity_params = selectivity_params,
                            catchability = target_scenario[[i]],
                            target = target_scenario[[i]])

    sim_scenario[[i]] <- project(params_scenario[[i]], 
                      effort = 0, 
                      dt = dt, 
                      fleetDynamics = TRUE, 
                      management = TRUE, 
                      multiFleet = FALSE,
                      price = price_forward, 
                      cost = cost_forward, 
                      diet_steps = 0, 
                      ke = ke,  
                      initial_effort = initial_effort_scenario,
                      scaling_price = scaling_price,
                      Blevel_management = Blevel_management,
                      initial_n = initial_n_scenario,
                      initial_n_pp = initial_n_pp_scenario, 
                      initial_n_bb = initial_n_bb_scenario)
  
    names(sim_scenario)[i]<-names(target_scenario)[i]
  
  } 
  
  return(sim_scenario)
}

# reduce number of runs as running to longer time. 
# target_scenario<-target_scenario[c("noCompetition","statusQuo", "fullCompetition")]
sim_scenario<-runModel(target_scenario)

```

#-----------------------------------------
# plots of comparison 
#----------------------------------------------

```{r}

### delete unfished as not used
sim_scenario$unfished<-NULL

# order scenarios
a = c("statusQuo","noCompetition","fullCompetition","noBycatch","MoreUnderQuota","MoreTarget")
b = c("Status Quo","No Comp.","Max Comp.", "Bycatch","Under-utilised", "Valuable")

# order fleets 
d = c("SET-SH","SET-US","SSG","SET-DS","SED")

# rename species  
spNames<-c("Lanternfish","Whiting","Squid","Perch","Mackerel","Redfish","Deep shark","Morwong","Flathead","Dories","Blue warehou","Orange roughy","Blue granadier","Silver warehou","Gemfish","Pink ling","Sawshark","Gummy shark","School shark")

# reorder indicators 
e = c("profit", "yield", "effort", "Fref","Nref48", "Nref40","Nref20","slope", "biomassTarget","biomassSens","biomass")
f = c("Profit", "Yield", "Effort", "Active fleets","Spp above Bmey","Spp above Bmsy","Spp above Blim", "Slope","Biomass target", "Biomass sensitive","Biomass")

#### fig 4 - scenarios and model dynamics  ----

# plot interaction matrix
plot_matrix = plotFleetMatrix(a,b,target_scenario)$plot_matrix 

# plot fleet effort 
col_values<-c("#b2182b", "#ef8a62", "#d1e5f0","#67a9cf", "#2166ac")
plot_effort = plotFleetEffort(a,b, sim_scenario, sim, col_values)

# plot trends in indicators  
col_values<-c("#7b3294","#c2a5cf","#a6dba0","#008837")
plot_indiTrend<-indicatorsTrend(a,b, sim_scenario, sim, col_values) # biomass is biomass of target
plot_all<-plot_indiTrend$plot_indiTrend

# all plots 
library(patchwork)
setwd("/Users/camillan/Dropbox/Mizer-fleet_extension/plot/FD/Final")
# other  trials
setwd("/Users/camillan/Desktop")

# tiff("Fig4.tiff", height=13, width=16, units ='in', res=300) # to 2040
# tiff("FigS9.tiff", height=13, width=16, units ='in', res=300) # to 2100
# plot_matrix / plot_effort / plot_all + plot_layout (nrow = 3, heights = c(2.2,1.4,1.4))
# dev.off()

# pdf("Fig4.pdf", height=13, width=16) # to 2040
# pdf("FigS9.pdf", height=13, width=16) # to 2100
# pdf("EQL_no_erepro_fix.pdf", height=13, width=16) to 2500 when is the system reaching  eql? 
pdf("Fig4_no_erepro_fix.pdf", height=13, width=16)
plot_matrix / plot_effort / plot_all + plot_layout (nrow = 3, heights = c(2.2,1.4,1.4))
dev.off()

##### fig 5 - trade-off plot -----

# avoid scenarios abbreviation for this fig 
b = c("Status Quo","No Competition","Max Competition", "Bycatch","Under-utilised", "Valuable")

indi<-indicators(sim_scenario, management = TRUE) 
df_plot = indi$df_plot
col_values3<-c("#7fbf7b","#af8dc3")
lolliIndicator = plotIndicators(a,b,df_plot, col_values3, scenarios = "all")$lolliIndicator 

# if need to patch a blank space 
blank<-ggplot()+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank())

# pdf("Fig5.pdf", height=6, width=7) # to 2040 
# pdf("FigS10.pdf", height=6, width=7) # to 2100
pdf("FigS10_no_erepro_fix.pdf", height=6, width=7) # to 2040
lolliIndicator
dev.off()


# save until here only if you are running the model to 2100


```

#-----------------------------------------
# additional plots 
#----------------------------------------------

```{r}

# repeat color for fleets above 
col_values<-c("#b2182b", "#ef8a62", "#d1e5f0","#67a9cf", "#2166ac")

plot_list<-list()
names(sim_scenario)

for(i in 1:length(sim_scenario)){
  plot_list[[i]]<-plotSppTrends(sim_scenario[[i]])
  names(plot_list)[i] <- names(sim_scenario)[i]
}

plot_list$noCompetition
  
setwd("/Users/camillan/Dropbox/Mizer-fleet_extension/plot/FD/Final")
for(i in 1:length(plot_list)){

  pdf(paste("FigS3_no_erepro_fix",names(plot_list)[i],".pdf", sep = "" ), height=13, width=13) #, units ='in', res=300)
  print(plot_list[[i]])
  dev.off()
  
  # tiff(paste("FigS3_",names(plot_list)[i],".tiff", sep = "" ), height=13, width=13, units ='in', res=300)
  # print(plot_list[[i]])
  # dev.off()
  
}

# explore details 
# why decreases in effort for teh SET-SH in less bycatch?
a<-sim_scenario$statusQuo
b<-sim_scenario$noBycatch

# species below 40 - same
spa<-filter(a@BioOut[[2]], fleet == "SET-SH", bioLim == "bio40check")
spb<-filter(b@BioOut[[2]], fleet == "SET-SH", bioLim == "bio40check")

trial<-a@params@target 
trial<-as_data_frame(trial) %>% 
  select(spa$species)

trial2<-b@params@target 
trial2<-as_data_frame(trial2) %>% 
  select(spa$species)

trial[4,] # status
trial2[4,] # no bycatch: more  

```

